function omtoolspath = setomtools(omtoolspath)

% written by:  Jonathan Jacobs
%              March 2017

% Does 'OMtools' folder exist? It can exist in a number of places:
% original location: matlabroot.  No longer a good idea, but will allow it.
% other locations: inside folder containing MATLAB; inside toolbox
% or even in home directory 'MATLAB' folder.

if nargin == 0
   disp('setomtools requires a valid OMtools path, as generated by findomtools')
   return
end

%sep = filesep;
omtf = size(omtoolspath,1);

if omtf < 1
   disp('Could not find an OMtools folder. Make sure it is installed in an appropriate location.')
   disp('Allowed directories are: matlabroot; the folder containing matlabroot; ')
   disp('the MATLAB toolbox folder (against Mathworks rules!!!); ')
   disp('inside your personal MATLAB directory in your home directory.')
   omtoolspath = '';
   return
elseif omtf == 1
   %omtoolspath = char(omtoolspath{1});
   disp( ['Using the OMtools located at ' omtoolspath])
elseif omtf > 1
   disp('Multiple OMtools folders found:')
   for m = 1:omtf
      disp([num2str(m) ': ' char(omtoolspath{m}) ] )
   end
   disp([newline 'Best practice is to use one in your home directory.'])
   disp('Which one would you like to use? ')
   choice = 0;
   while choice < 1
      choice = input('--> ');
   end
   temp = char(omtoolspath{omtf});
   disp('Would you like to inactivate the other installations? (y/n)')
   yorn=input('--> ','s');
   if strcmpi(yorn,'y')
      for m=1:omtf
         if choice == m
            % do nothing
         else
            % add an 'x' into the name of the other omtools folders
            a = strfind(omtoolspath{m}, 'OMtools');
            b = [ omtoolspath{m}(1:a-1) 'OM_x_' omtoolspath{m}(a+2:end) ];
            movefile(omtoolspath{m}, b);
         end
      end
   end
   omtoolspath = temp;
end

cd(omtoolspath)