% frameup.m: Interactive, GUI-driven program to let the user determine
% the eye position of the subject in a video.  The video must be in
% .AVI format (uncompressed for UNIX computers).
%
% The user goes through the video frame by frame, and selects two constant 
% landmarks (e.g. the lateral and medial canthi) that serve as points of
% reference, and two points (e.g. medial and lateral limbus) that mark the
% position of the eye.  The program then calculates the pupil center.
% (NOTE -- As of Feb 2005, this program is only being used to record 
% horizontal eye movements, but most of the structure for vertical selection
% is in place.)  Selected points are saved in a text file that is named the
% same as the video file that was used to generate it.  Use the program
% "vidwaveform" (in ongoing development) to analyze the point file.
%
% The user can also create a movie of the analyzed frames by using the playback
% feature and selecting the "make movie" control.  The movie will be saved as 
% a series of still frames (jpg format) that can then be assembled into a movie
% using (e.g.) QuickTime Pro's "Open Image Sequence" feature.  (While it is 
% possible to generate an AVI directly from MATLAB, the quality and size of the
% output leaves something to be desired.)
%
% Future development may include automatic (with user supervision/veto)
% detection of pupil centroid using routines from the image processing toolbox.
%
% written by:  Jonathan Jacobs
%              September 2004 - February 2005  (last mod: 02/09/05)

function frameup(null)

global avimov

% is the window already open?
playFig = -1;
wl = get(0,'Children');
for i = 1:length(wl)
   if strcmp(get(wl(i),'Name'),'Frame Viewer'), playFig=wl(i); end
end

% if not, create it.  (if 'yes' then make it frontmost)
if playFig < 0
   playFig = figure('Position',[100 100 800 600],...
   			  'Resize','off',...
              'Name','Frame Viewer','NumberTitle','off', ...
              'Menubar','none','Tag','frameup: uneditable', ...
              'DeleteFcn',['clear global avimov cH ' ...
              					'init_xlims init_ylims savedpts']);
	oldFigPos = get(playFig,'Position');
	playAx = axes('position', [0.1300  0.250  0.7750  0.700]);
	%set(playAx, 'DataAspectRatio', [1 1 1])
	axis image %%off
	set(playAx,'XLim',[0 720], 'YLim',[0 480])
	set(playAx,'xticklabel','')
	set(playAx,'yticklabel','')
	t=text(150, 240, ['Click "Load..." to select an AVI-format '...
							'movie to analyze']);
	set(t,'FontSize',14)
   box on
 else
   figure(playFig)
   return
end

% start with everything full scale
max_wid = 0.775;  max_hgt = 0.700;
ax_size = 1;

numFrames = 0;
if ~isempty(avimov)
   temp = size(avimov); numFrames = max(temp);
end

% create controls
fig_ht = 420;

movienameH = uicontrol(playFig, 'Style', 'text',...
   'Position', [310 575 180 20],...
   'String', 'Current movie:  * none loaded *',...
   'HorizontalAlignment','left',....
   'BackGroundColor',[0.75 0.75 0.75],'ForeGroundColor','black',...
   'Tooltip','Movie currently loaded');

uicontrol(playFig,'Style','Frame','Units', 'pixels',...
   'BackgroundColor',[0.25 0.25 0.25],'Position',[20 10 320 120])
uicontrol(playFig,'Style','Frame','Units', 'pixels',...
   'BackgroundColor',[0.25 0.25 0.25],'Position',[350 10 410 75])
uicontrol(playFig,'Style','Frame','Units', 'pixels',...
   'BackgroundColor',[0.25 0.25 0.25],'Position',[350 90 410 40])

y_pos = 100;
cropBH = uicontrol(playFig, 'Style', 'Toggle',...
   'Position', [375 y_pos 50 20],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Crop the video window',...
   'String', 'Crop','Callback', ['frameAct(''crop'');'] );

cropresetBH = uicontrol(playFig, 'Style', 'pushbutton',...
   'Position', [430 y_pos 50 20],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Uncrop the video window',...
   'String', 'Reset','Callback', ['frameAct(''uncrop'');'] );

uicontrol(playFig, 'Style', 'text',...
   'Position', [490 y_pos 60 20], 'String', 'Video size');
ax_size_sliH = uicontrol(playFig, 'Style', 'slider',...
   'Position', [ 552 y_pos 150 20],...
   'Min', 0.5, 'Max', 1.0, 'Value', ax_size,...
   'Visible','on',...
   'Tooltip','Scale the video window',...
   'Callback',['frameAct(''resize_ax_sli'');']);
ax_size_txtH = uicontrol(playFig, 'Style', 'edit',...
   'Position', [705 y_pos 40 20],...
   'String', num2str(get(ax_size_sliH,'Value'),3),...
   'BackGroundColor','magenta','ForeGroundColor','white',...
   'Tooltip','Scale the video window',...
   'Callback', ['frameAct(''resize_ax_txt'');']);

uicontrol(playFig, 'Style', 'text',...
   'Position', [30 y_pos 42 20], 'String', 'Start');
start_sliH = uicontrol(playFig, 'Style', 'slider',...
   'Position', [ 75 y_pos 200 20],...
   'Min', 1, 'Max', 2, 'Value', 1,...
   'Visible','on',...
   'Tooltip','Set the start time',...
   'Callback',['frameAct(''start_sli'');']);
start_txtH = uicontrol(playFig, 'Style', 'edit',...
   'Position', [280 y_pos 50 20],...
   'String', num2str(get(start_sliH, 'Value')),...
   'BackGroundColor','magenta','ForeGroundColor','white',...
   'Tooltip','Set the start time (samples)',...
   'Callback', ['frameAct(''start_txt'');'] );

y_pos=y_pos-25;
uicontrol(playFig, 'Style', 'text',...  
   'Position', [30 y_pos 42 20], 'String', 'Stop');
stop_sliH = uicontrol(playFig, 'Style', 'slider',...
   'Position', [ 75 y_pos 200 20],...
   'Min', 1, 'Max', 2, 'Value', 1,...
   'Visible','on',... 
   'Tooltip','Set the stop time',...
   'Callback',['frameAct(''stop_sli'');']);
stop_txtH = uicontrol(playFig, 'Style', 'edit',...
   'Position', [280 y_pos 50 20],...
   'String', num2str(get(stop_sliH, 'Value')),...
   'BackGroundColor','magenta','ForeGroundColor','white',...
   'Tooltip','Set the stop time (samples)',...
   'Callback', ['frameAct(''stop_txt'');'] );

y_pos=y_pos-25;
uicontrol(playFig, 'Style', 'text',...
   'Position', [30 y_pos 42 20], 'String', 'Current');
cur_sliH = uicontrol(playFig, 'Style', 'slider',...
   'Position', [ 75 y_pos 200 20],...
   'Min', 1, 'Max', 2, 'Value', 1,...
   'Visible','on',...
   'Tooltip','Shows the current frame in the video',...
   'Callback',['frameAct(''cur_sli'');']);
cur_txtH = uicontrol(playFig, 'Style', 'edit',...
   'Position', [280 y_pos 50 20],...
   'String', num2str(get(cur_sliH, 'Value')),...
   'BackGroundColor','magenta','ForeGroundColor','white',...
   'Tooltip','Shows the current frame in the video',...
   'Callback', ['frameAct(''cur_txt'');'] );

y_pos = 50;
backH = uicontrol(playFig, 'Style', 'Pushbutton',...
   'Position', [380 y_pos-30 50 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Tooltip','Go back one frame',...
   'String', '<','Callback', ['frameAct(''back'')'] );

fwdH = uicontrol(playFig, 'Style', 'Pushbutton',...
   'Position', [435 y_pos-30 50 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Tooltip','Go forward one frame',...
   'String', '>','Callback', ['frameAct(''fwd'')'] );

uicontrol(playFig, 'Style', 'text',...
   'Position', [235 y_pos-28 40 20],...
   'String', 'Frames',...
   'BackGroundColor',[0.75 0.75 0.75],'ForeGroundColor','black');

totalFramesH = uicontrol(playFig, 'Style', 'text',...
   'Position', [280 y_pos-28 50 20],...
   'String', num2str(numFrames),...
   'BackGroundColor',[0.75 0.75 0.75],'ForeGroundColor','black',...
   'Tooltip','Total Frames');



pt1x = uicontrol(playFig, 'Style', 'edit',...
   'Position', [535 y_pos 50 20],...
   'String', '',...
   'BackGroundColor','cyan','ForeGroundColor','black',...
   'Tooltip','Change x coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );
pt1y = uicontrol(playFig, 'Style', 'edit',...
   'Position', [535 y_pos-25 50 20],...
   'String', '',...
   'BackGroundColor','cyan','ForeGroundColor','black',...
   'Tooltip','Change y coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );

pt2x = uicontrol(playFig, 'Style', 'edit',...
   'Position', [590 y_pos 50 20],...
   'String', '',...
   'BackGroundColor','green','ForeGroundColor','black',...
   'Tooltip','Change x coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );
pt2y = uicontrol(playFig, 'Style', 'edit',...
   'Position', [590 y_pos-25 50 20],...
   'String', '',...
   'BackGroundColor','green','ForeGroundColor','black',...
   'Tooltip','Change y coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );

pt3x = uicontrol(playFig, 'Style', 'edit',...
   'Position', [645 y_pos 50 20],...
   'String', '',...
   'BackGroundColor','green','ForeGroundColor','black',...
   'Tooltip','Change x coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );
pt3y = uicontrol(playFig, 'Style', 'edit',...
   'Position', [645 y_pos-25 50 20],...
   'String', '',...
   'BackGroundColor','green','ForeGroundColor','black',...
   'Tooltip','Change y coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );

pt4x = uicontrol(playFig, 'Style', 'edit',...
   'Position', [700 y_pos 50 20],...
   'String', '',...
   'BackGroundColor','cyan','ForeGroundColor','black',...
   'Tooltip','Change x coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );
pt4y = uicontrol(playFig, 'Style', 'edit',...
   'Position', [700 y_pos-25 50 20],...
   'String', '',...
   'BackGroundColor','cyan','ForeGroundColor','black',...
   'Tooltip','Change y coordinate for this point',...
   'Callback', ['frameAct(''mod_pt'');'] );

loadH = uicontrol(playFig, 'Style', 'Pushbutton',...
   'Position', [30 y_pos-30 45 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Tooltip','Load a video to analyze',...
   'String', 'Load...','Callback', ['frameAct(''load'')'] );

playH = uicontrol(playFig, 'Style', 'pushbutton',...
   'Position', [85 y_pos-30 45 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Play the movie',...
   'String', 'Play','Callback', ['frameAct(''play'');'] );

makemovieH = uicontrol(playFig, 'Style', 'checkbox',...
   'Position', [135 y_pos-30 80 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Save video+points as a movie',...
   'String', 'Make Movie','Callback', ['frameAct('''');'] );

pickPtsH = uicontrol(playFig, 'Style', 'Toggle',...
   'Position', [355 y_pos 50 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Select points for this frame',...
   'String', 'Pick Pts','Callback', ['frameAct(''pick'');'] );

rejectPtsH = uicontrol(playFig, 'Style', 'pushbutton',...
   'Position', [410 y_pos 50 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Reject the points selected for this frame',...
   'String', 'Reject','Callback', ['frameAct(''reject'');'] );

savePtsH = uicontrol(playFig, 'Style', 'pushbutton',...
   'Position', [465 y_pos 50 25],'UserData',0,...
   'BackGroundColor',[0.75 0.75 0.75],...
   'Value',0,'Tooltip','Save all selected points to a text file',...
   'String', 'Save Pts','Callback', ['frameAct(''savepts'');'] );



controlH = {playFig playAx loadH backH fwdH makemovieH totalFramesH ...
            pickPtsH rejectPtsH savePtsH playH ...
            pt1x pt1y pt2x pt2y pt3x pt3y pt4x pt4y ...
			   ax_size_sliH ax_size_txtH ...
			   start_sliH start_txtH stop_sliH stop_txtH cur_sliH cur_txtH ...
			   cropBH cropresetBH movienameH};
set(gcf,'UserData',controlH)
