%% PWcalc.m: loop to calculate the PH, PW based on the equations Dan put
%% in the PG block.

%% for the LINEAR PG blocks  (not the nonlin one)
for i = 1:50
   ph(i) = 590*i/(7.5+i);
   pw(i) = -0.0089 - i*0.00132;
end

ph=ph*0.26;

%%  These are values measured directly by running PG (as part of testbed)
%%  The  pulse height is the same as generated by the loop (when the 0.26 gain
%%  is used).  The pulse width is quite different.
%%  stm=[1 2 3 4 5 6 7 8 10 12 15 17 20 22 25 27 30 32 35 37 40 42 45 47 50]';
%%  pw_meas=[12 13 14 16 17 18 20 21 24 26 30 33 38 40 43 46 49 53 56 59 63 66 69 73 75]';